/* Generated By:JavaCC: Do not edit this line. LanguageConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LanguageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int False = 5;
  /** RegularExpression Id. */
  int Var = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int symbA = 8;
  /** RegularExpression Id. */
  int equality = 9;
  /** RegularExpression Id. */
  int and = 10;
  /** RegularExpression Id. */
  int neg = 11;
  /** RegularExpression Id. */
  int skipp = 12;
  /** RegularExpression Id. */
  int equal = 13;
  /** RegularExpression Id. */
  int semicolon = 14;
  /** RegularExpression Id. */
  int If = 15;
  /** RegularExpression Id. */
  int Else = 16;
  /** RegularExpression Id. */
  int While = 17;
  /** RegularExpression Id. */
  int Do = 18;
  /** RegularExpression Id. */
  int Then = 19;
  /** RegularExpression Id. */
  int True = 20;
  /** RegularExpression Id. */
  int left = 21;
  /** RegularExpression Id. */
  int right = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"ff\"",
    "<Var>",
    "<NUM>",
    "<symbA>",
    "\"==\"",
    "\"^\"",
    "\"!\"",
    "\"skip\"",
    "\":=\"",
    "\";\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"then\"",
    "\"tt\"",
    "\"(\"",
    "\")\"",
  };

}
